language: cpp
os: linux
sudo: true
dist: xenial
cache:
  ccache: true
  directories:
  - ${HOME}/.ccache

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - clang-6.0
    - g++-7
    - python-pip
    - libcurl4-openssl-dev
    - libelf-dev
    - libdw-dev

env:
  global:
  - LOCAL=${HOME}/.local
  - PATH=${LOCAL}/bin:${PATH}

before_script:
- cmake --version
- '[ -z "$BOOST_MINOR" ] || wget -O "boost_1_${BOOST_MINOR}_0.tar.gz" "https://dl.bintray.com/boostorg/release/1.${BOOST_MINOR}.0/source/boost_1_${BOOST_MINOR}_0.tar.gz"'
- '[ -z "$BOOST_MINOR" ] || tar xzf "boost_1_${BOOST_MINOR}_0.tar.gz"'
- '[ -z "$BOOST_MINOR" ] || cd "boost_1_${BOOST_MINOR}_0"'
- '[ -z "$BOOST_MINOR" ] || ./bootstrap.sh --with-libraries=system,thread,context,coroutine,atomic,date_time'
- '[ -z "$BOOST_MINOR" ] || mkdir build'
- '[ -z "$BOOST_MINOR" ] || ./b2 --build-dir=build'
- '[ -z "$BOOST_MINOR" ] || sudo ./b2 --build-dir=build install'
- cd ${TRAVIS_BUILD_DIR}
- mkdir -p ${TRAVIS_BUILD_DIR}/build
- cd ${TRAVIS_BUILD_DIR}/build

matrix:
  include:
  - name: clang 6 release
    env:
    - CXX_COMPILER: clang++-6.0
    - BOOST_MINOR: 66
    script:
    - ${TRAVIS_BUILD_DIR}/scripts/travis/build.sh
  - name: gcc 7 debug+coverage
    env:
    - CXX_COMPILER: g++-7
    - BOOST_MINOR: 66
    script:
    - ${TRAVIS_BUILD_DIR}/scripts/travis/coverage.sh
    after_success:
    - bash <(curl -s https://codecov.io/bash)
  - name: clang 6 boost 1.70
    env:
    - CXX_COMPILER: clang++-6.0
    - BOOST_MINOR: 70
    script:
    - ${TRAVIS_BUILD_DIR}/scripts/travis/build.sh
  - name: conan auto detect
    script:
    - ${TRAVIS_BUILD_DIR}/scripts/travis/conan.sh
